# deploys solely the crds
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crd
spec:
  interval: 5m
  path: "./deploy/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eso