apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: "0.3.10"
      sourceRef:
        kind: HelmRepository
        name: eso
      interval: 1m
  values: {}